plot4 <- function(DF=NULL, bg="transparent") {
	#Plot the fourth graphic. Read the data file if necessary. 
	#Set the plot background to the specified value. 
	#This function reuses code from to generate some of the
	#other graphics. 

	#Import some code used to generate graphics. 
	source("plot2.R")
	source("plot3.R")
	
	#Read the data file if necessary
	if (is.null(DF)) {
		source("read_data.R")
		DF <- read_data()
	}

	#Set the background color to the specified value
	par(bg=bg)

	#Set the number of columns and rows for the plots. 
	par(mfrow=c(2,2))

	#The top left plot is identical to plot #2 but with a 
	#different y axis label
	plot2(DF, bg=bg, ylab="Global Active Power")

	#The top right plot is voltage against time. 
	#Generated by a method in this file. 
	plot_voltage(DF)

	#The bottom left plot is identical to plot 3, but 
	#lacking the legend border. 
	plot3(DF, bg=bg, lgndbty="n")

	#The bottom right plot is global reactive power against
	#time. Generated by a method in this file. 
	plot_global_reactive_power(DF)
}

plot_and_print_4 <- function(DF=NULL, bg="transparent") {

	#plot the 4th graphic
	plot4(DF, bg=bg)

	#print the graphic to disk. 
	dev.copy(png, filename="plot4.png", height=480, width=480)
	dev.off()
}

plot_voltage <- function(DF) {
	#Plot voltage against time. 
	plot(DF$DateTime, DF$Voltage, type="l",
		xlab="datetime",
		ylab="Voltage",
		main="")
}

plot_global_reactive_power <- function(DF) {
	#Plot the global reactive power against time. 
	plot(DF$DateTime, DF$Global_reactive_power, type="l",
		xlab="datetime",
		ylab="Global_reactive_power",
		main="")
}